### PR TITLE
fix: pass the kafka admin url to the topics metrics

### PR DESCRIPTION
**Pull request by riccardo-forina**

### CODE REVIEW

**Comment by riccardo-forina** [comment]
We have to call the api on refresh. We'll also have to derive the total number of partitions from this api. It's more flexible to call the api from the metrics directly, since we have to do it to fetch the actual metrics.

**Comment by pmuir** [comment]
Apart from getting the list of topics, as we discussed, you don't need to call the admin api.

The total number of partitions comes from the metrics api - `kafka_controller_kafkacontroller_global_partition_count` - not the admin api

Why do we need to call the api on refresh? Wouldn't this be passed in as a state object (and so refreshed when needed)? What metrics that we fetch require calling the admin api?

I understand it may be more flexible to just call the APIs from everywhere, but that fundamentally breaks separation of concerns.

**Comment by riccardo-forina** [comment]
Metrics derived from the response of the metrics api are valid only for the given time frame. In the designs the total partitions count isn't clearly tied to a time frame, nor there is an option to specify one.

That made me assume that the best way to get that information would have been to ask the admin api directly.

About the separation of concern I can agree, and we could pass a Promise returning function to fetch the topics instead of the raw api info needed to make the call. That would keep the two parts decoupled.

**Comment by riccardo-forina** [comment]
Refreshing the topics list when clicking refresh would ensure getting the latest data from the system. If a topic has been created by someone else in the meanwhile, we would get it without having to go to another page and back to the metrics.

This at least unless we plan to have a central point where we control all the data and their polling, but it doesn't look to be the case right now?

**Pull request closed without merging**
